#
# Connects to Google Assistant
#

google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include google_assistant_service_account.json
  expose_by_default: false
  entity_config:
    light.bedroom_nightstand:
      expose: true
    light.kitchen_corner_window_light:
      expose: true
    light.office_lightstrip:
      expose: true
    light.ambilight:
      expose: true
    fan.standing_fan:
      expose: true

tts:
  - platform: google_translate
    service_name: google_say
    base_url: !secret http_url
