#
# Connects to Google Assistant
#

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  entity_config:
    light.corner_window_light:
      expose: true
    light.office_lightstrip:
      expose: true
    media_player.tv_screen:
      expose: true
