#
# Contains configurations for various graphs.
#

history_graph:

  power_usage:
    name: Power usage
    hours_to_show: 48
    entities:
      - sensor.dishwasher_power_usage

  server_statistics:
    name: Server statistics
    hours_to_show: 48
    entities:
      - sensor.disk_use_percent_config
      - sensor.memory_use_percent
      - sensor.processor_use
