#
# Configures the history.
#

history:
  exclude:
    entities:
      - sensor.since_last_boot_templated

recorder:
  purge_keep_days: 1
  exclude:
    entities:
      - sensor.since_last_boot_templated
