#
# Provides information and notifications about the washing machine and dryer.
#

input_select:
  washingmachine_status:
    name: washingmachine_status
    options:
      - Idle
      - Running
#  dryer_status:
#    name: dryer_status
#    options:
#      - Idle
#      - Running

sensor:
  - platform: template
    sensors:
      washingmachine_status:
        value_template: "{{ states.input_select.washingmachine_status.state }}"
        icon_template: mdi:washing-machine
        friendly_name: Washing machine status
#      dryer_status:
#        value_template: "{{ states.input_select.dryer_status.state }}"
#        icon_template: mdi:tumble-dryer
#        friendly_name: Dryer status

automation:
  # Set the washing machine to running state when the power usage goes up and it is in idle state
  - alias: washingmachine_started
    trigger:
      - platform: numeric_state
        entity_id: sensor.powerplug_washingmachine_power
        above: 5
        for:
          minutes: 1
    condition:
      - condition: state
        entity_id: input_select.washingmachine_status
        state: Idle
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washingmachine_status
          option: Running

  # Set washing machine to idle state when power drops and it is in running state
  - alias: washingmachine_completed
    trigger:
      - platform: numeric_state
        entity_id: sensor.powerplug_washingmachine_power
        below: 1
        for:
          minutes: 1
    condition:
      - condition: state
        entity_id: input_select.washingmachine_status
        state: Running
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washingmachine_status
          option: Idle
      - service: notify.home
        data:
          title: Washing machine finished
          message: The washing machine has finished and the laundry can be moved to the dryer
      - service: script.sonos_say
        data:
          entity_id: media_player.kitchen
          volume: 30
          message: The washing machine has finished and the laundry can be moved to the dryer
          delay: 00:00:05

#  # Set the dryer to running state when the power usage goes up and it is in idle state
#  - alias: dryer_started
#    trigger:
#      - platform: numeric_state
#        entity_id: sensor.dryer_power_usage
#        above: 5
#        for:
#          minutes: 1
#    condition:
#      - condition: state
#        entity_id: input_select.dryer_status
#        state: Idle
#    action:
#      - service: input_select.select_option
#        data:
#          entity_id: input_select.dryer_status
#          option: Running

#  # Set dryer to idle state when power drops and it is in running state
#  - alias: dryer_completed
#    trigger:
#      - platform: numeric_state
#        entity_id: sensor.dryer_power_usage
#        below: 1
#        for:
#          minutes: 1
#    condition:
#      - condition: state
#        entity_id: input_select.dryer_status
#        state: Running
#    action:
#      - service: input_select.select_option
#        data:
#          entity_id: input_select.dryer_status
#          option: Idle
#      - service: notify.home
#        data:
#          title: Dryer finished
#          message: The dryer has finished
#      - service: script.sonos_say
#        data:
#          media_player: kitchen
#          volume: 30
#          message: The dryer has finished
#          delay: 00:00:04
