#
# Configures all the lights of the home.
#

light:
  - platform: group
    unique_id: light.bedroom_nightstand
    name: Nightstand
    entities:
      - light.bedroom_nightstand_left
      - light.bedroom_nightstand_right
