#
# Configures all the lights of the home.
#

homeassistant:
  customize:
    sensor.daylight:
      hidden: true

light:
  - platform: group
    name: Bedroom nightstand
    entities:
      - light.bedroom_nightstand_left
      - light.bedroom_nightstand_right

group:
  bedroom_lights:
    name: Lights
    control: hidden
    entities:
      - light.bedroom_nightstand
