#
# Location and state of the cellphone
#

homeassistant:
  customize:
    device_tracker.iphone:
      hidden: true
    sensor.iphone_battery_level:
      friendly_name: Battery level
    sensor.iphone_battery_state:
      friendly_name: State
    automation.notify_when_location_changes:
      hidden: true

mobile_app:

group:
  phone:
    name: Phone
    control: hidden
    entities:
      - sensor.iphone_location
      - sensor.iphone_battery_level
      - sensor.iphone_battery_state

sensor:
  - platform: template
    sensors:
      iphone_location:
        entity_id:
          - device_tracker.iphone
        friendly_name: Location
        icon_template: mdi:map-marker
        value_template: >-
          {% if is_state('device_tracker.iphone', 'home') %}
            Home
          {% elif is_state('device_tracker.iphone', 'Work') %}
            Work
          {% else %}
            Away
          {% endif %}

automation:
  - id: notify_when_location_changes
    alias: Notify when location changes
    trigger:
      platform: state
      entity_id: sensor.iphone_location
    action:
      service: notify.phone
      data_template:
        title: "Your location changed"
        message: "Your location changed to '{{ states.sensor.iphone_location.state }}'."
