#
# Reads server values, such as CPU usage
#

homeassistant:
  customize:
    automation.server_cpu_high:
      hidden: true
      friendly_name: High server CPU usage
    automation.server_memory_high:
      hidden: true
      friendly_name: High server memory usage
    automation.server_disk_high:
      hidden: true
      friendly_name: High server disk space usage
    sensor.disk_use_percent_config:
      friendly_name: Disk
    sensor.memory_use_percent:
      friendly_name: Memory
    sensor.processor_use:
      friendly_name: CPU
#    sensor.since_last_boot_templated:
#      friendly_name: Uptime
#      icon: mdi:clock
    sensor.since_last_boot:
      hidden: true

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: processor_use
#      - type: since_last_boot
#  - platform: template
#    sensors:
#      since_last_boot_templated:
#        value_template: >-
#          {% set time = states.sensor.since_last_boot.state.split('.')[0] %}
#
#          {% set timeParts = time.split(',') %}
#          {% if timeParts | length == 2 %}
#            {% set output = timeParts[0] + ', ' %}
#            {% set time = timeParts[1] %}
#          {% elif timeParts | length == 1 %}
#            {% set output = '' %}
#            {% set time = timeParts[0] %}
#          {% endif %}
#
#          {% set parts = time.split(':') %}
#          {% set hours = parts[0] | int %}
#          {% set minutes = parts[1] | int %}

#          {% if hours == 1 %}
#            {% set output = output + '1 hour and ' %}
#          {% else %}
#            {% set output = output + hours | string + ' hours and ' %}
#          {% endif %}

#          {% if minutes == 1 %}
#            {% set output = output + '1 minute' %}
#          {% else %}
#            {% set output = output + minutes | string + ' minutes' %}
#          {% endif %}
#          {{ output }}

group:
  server:
    name: Server
    control: hidden
    entities:
      - sensor.disk_use_percent_config
      - sensor.memory_use_percent
      - sensor.processor_use
#      - sensor.since_last_boot_templated

automation:
  - alias: server_cpu_high
    trigger:
      - platform: numeric_state
        entity_id: sensor.processor_use
        above: 20
    action:
      - service: notify.phone
        data_template:
          title: "Server machine working hard"
          message: "High CPU usage on the server: {{ states.sensor.processor_use.state }}%"
  - alias: server_memory_high
    trigger:
      - platform: numeric_state
        entity_id: sensor.memory_use_percent
        above: 40
    action:
      - service: notify.phone
        data_template:
          title: "Server machine working hard"
          message: "High memory usage on the server: {{ states.sensor.memory_use_percent.state }}%"
  - alias: server_disk_high
    trigger:
      - platform: numeric_state
        entity_id: sensor.disk_use_percent_config
        above: 40
    action:
      - service: notify.phone
        data_template:
          title: "Server using a lot of disk space"
          message: "High disk space usage on the server: {{ states.sensor.disk_use_percent_config.state }}%"
