#
# Reads server values, such as CPU usage
#

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

#automation:
#  - alias: server_cpu_high
#    trigger:
#      - platform: numeric_state
#        entity_id: sensor.processor_use
#        above: 20
#    action:
#      - service: notify.phone
#        data_template:
#          title: "Server machine working hard"
#          message: "High CPU usage on the server: {{ states.sensor.processor_use.state }}%"
#  - alias: server_memory_high
#    trigger:
#      - platform: numeric_state
#        entity_id: sensor.memory_use_percent
#        above: 40
#    action:
#      - service: notify.phone
#        data_template:
#          title: "Server machine working hard"
#          message: "High memory usage on the server: {{ states.sensor.memory_use_percent.state }}%"
#  - alias: server_disk_high
#    trigger:
#      - platform: numeric_state
#        entity_id: sensor.disk_use_percent_config
#        above: 40
#    action:
#      - service: notify.phone
#        data_template:
#          title: "Server using a lot of disk space"
#          message: "High disk space usage on the server: {{ states.sensor.disk_use_percent_config.state }}%"
