#
# Controls all sound components in the home
#

homeassistant:
  customize:
    script.sonos_say:
      hidden: true

sonos:
  media_player:
    hosts:
      - !secret sonos_playbar_hostname
      - !secret sonos_kitchen_hostname
      - !secret sonos_bedroom_hostname

script:
  sonos_say:
    alias: "Sonos TTS script"
    sequence:
     - service: sonos.snapshot
       data_template:
         entity_id: "{{ 'media_player.' ~ media_player }}"
     - service: sonos.unjoin
       data_template:
         entity_id: "{{ 'media_player.' ~ media_player }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ 'media_player.' ~ media_player }}"
         volume_level: "{{ volume }}"
     - service: tts.google_say
       data_template:
         entity_id: "{{ 'media_player.' ~ media_player }}"
         message: "{{ message }}"
     - delay: "{{ delay }}"
     - service: sonos.restore
       data_template:
         entity_id: "{{ 'media_player.' ~ media_player }}"
