#
# Monitors SSL certificates to inform me about remaining days of validity.
#

sensor:
  - platform: template
    sensors:
      days_until_expires_home_assistant:
        unique_id: sensor.days_until_expires_home_assistant
        unit_of_measurement: days
        value_template: >-
          {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_home_anton_johansson_com'), 0) - as_timestamp(now())) / 86400) | int }}

#automation:
#  - alias: notify_when_home_assistant_ssl_cert_expires_soon
#    trigger:
#      platform: numeric_state
#      entity_id: sensor.days_until_expires_home_assistant
#      below: 20
#    action:
#      service: notify.phone
#      data_template:
#        title: "SSL certificate expires soon"
#        message: "Home Assistant SSL certificate expires in {{ states('sensor.days_until_expires_home_assistant') }} days!"
