---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  secretName: prometheus-certificate
  commonName: prometheus.anton-johansson.local
  dnsNames:
    - prometheus.anton-johansson.local
  issuerRef:
    name: anton-johansson-home-services-ca
    kind: ClusterIssuer
    group: cert-manager.io
