---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
rules:
  - apiGroups: ['certmanager.k8s.io']
    resources: [certificates, issuers, clusterissuers, orders, challenges]
    verbs: ['*']
  - apiGroups: ['']
    resources: [configmaps, secrets, events, services, pods]
    verbs: ['*']
  - apiGroups: [extensions, networking.k8s.io]
    resources: [ingresses]
    verbs: ['*']

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager
subjects:
  - name: cert-manager
    namespace: cert-manager
    kind: ServiceAccount

