language: python
python:
  - "3.4"
install:
  - HA_VERSION=$(cat home-assistant/.HA_VERSION)
  - pip3 install "homeassistant==$HA_VERSION"
  - pip3 install "pycrypto"
script:
  - hass -c home-assistant --script check_config
before_install:
  - cp travis-secrets.yaml home-assistant/secrets.yaml
