language: python
python:
  - "3.4"
install:
  - HA_VERSION=$(cat .HA_VERSION)
  - pip3 install "homeassistant==$HA_VERSION"
script:
  - hass -c . --script check_config
before_install:
  - cp travis-secrets.yaml secrets.yaml
