homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named packages
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret http_password

updater:

zwave:
  usb_path: /dev/ttyACM0

ios:

discovery:

conversation:

history:

recorder:
  purge_keep_days: 10

logbook:

map:

sun:

tts:
  - platform: google

cloud:

group: !include groups.yaml
script: !include scripts.yaml
zone: !include zones.yaml
