version: '2'

services:

  home-assistant:
    image: homeassistant/home-assistant:0.64.0
    container_name: home-assistant
    restart: always
    volumes:
      - /home/anton/home/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/zwave

  deconz:
    image: marthoc/deconz:amd64-2.05.11
    container_name: deconz
    restart: always
    volumes:
      - /home/anton/home/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443

  portainer:
    image: portainer/portainer:1.19.1
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/anton/home/portainer/data:/data

  nginx:
    image: nginx:1.13.11
    container_name: nginx
    restart: always
    volumes:
      - /home/anton/home/nginx/conf.d:/etc/nginx/conf.d
      - /home/anton/home/nginx/certificates:/etc/letsencrypt
      - /home/anton/home/nginx/letsencrypt:/data/letsencrypt
    ports:
      - 80:80
      - 443:443

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=anton-johansson
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - /home/anton/home/elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.4
    container_name: logstash
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    restart: always
    volumes:
      - /home/anton/home/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - /home/anton/home/logstash/config/template.json:/usr/share/logstash/config/template.json:ro
      - /home/anton/home/logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    container_name: kibana
    restart: always
    volumes:
      - /home/anton/home/kibana/config:/usr/share/kibana/config:ro
    depends_on:
      - elasticsearch

  logspout:
    build:
      context: logspout
    container_name: logspout
    environment:
      - ROUTE_URIS=logstash://logstash:5000
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - logstash
