version: '2'

services:

  home-assistant:
    image: homeassistant/home-assistant:0.64.0
    container_name: home-assistant
    restart: always
    network_mode: host
    volumes:
      - /home/anton/home/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0

  deconz:
    image: marthoc/deconz:amd64-2.05.11
    container_name: deconz
    restart: always
    network_mode: host
    volumes:
      - /home/anton/home/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
