version: '3.4'

networks:
  traefik-net:
    driver: bridge
  elasticsearch-net:
    driver: bridge
  logstash-net:
    driver: bridge

services:

  traefik:
    image: traefik:1.7.3-alpine
    container_name: traefik
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/traefik/acme.json:/acme.json
    restart: always
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    labels:
      traefik.enable: "true"
      traefik.port: 8080
      traefik.frontend.rule: "Host:traefik.anton-johansson.com"
      traefik.frontend.entryPoints: "https"
      traefik.frontend.whiteList.sourceRange: "192.168.1.0/24"
    command:
      - "--entryPoints=Name:http Address::80"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--api"
      - "--api.entryPoint=traefik"
      - "--api.dashboard=true"
      - "--docker"
      - "--docker.watch"
      - "--docker.exposedByDefault=false"
      - "--docker.endpoint=unix:///var/run/docker.sock"
      - "--docker.network=home_traefik-net"
      - "--acme"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=antoon.johansson@gmail.com"
      - "--traefikLog.format=json"
      - "--logLevel=INFO"

  home-assistant:
    image: homeassistant/home-assistant:0.64.0
    container_name: home-assistant
    networks:
      - traefik-net
    volumes:
      - /home/anton/home/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    devices:
      - /dev/ttyACM0:/dev/zwave
    labels:
      traefik.enable: "true"
      traefik.port: 8123
      traefik.frontend.rule: "Host:home.anton-johansson.com"
      traefik.frontend.entryPoints: "https"

  deconz:
    image: marthoc/deconz:amd64-2.05.11
    container_name: deconz
    networks:
      - traefik-net
    volumes:
      - /home/anton/home/deconz:/root/.local/share/dresden-elektronik/deCONZ
    restart: always
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
    labels:
      traefik.enable: "true"
      traefik.port: 8080
      traefik.frontend.rule: "Host:deconz.anton-johansson.com"
      traefik.frontend.entryPoints: "https"
      traefik.frontend.whiteList.sourceRange: "192.168.1.0/24"

  portainer:
    image: portainer/portainer:1.19.1
    container_name: portainer
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/anton/home/portainer/data:/data
    restart: always
    labels:
      traefik.enable: "true"
      traefik.port: 9000
      traefik.frontend.rule: "Host:portainer.anton-johansson.com"
      traefik.frontend.entryPoints: "https"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elasticsearch
    networks:
      - elasticsearch-net
      - traefik-net
    environment:
      - cluster.name=anton-johansson
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - /home/anton/home/elasticsearch/data:/usr/share/elasticsearch/data
    labels:
      traefik.enable: "true"
      traefik.port: 9200
      traefik.frontend.rule: "Host:elasticsearch.anton-johansson.com"
      traefik.frontend.entryPoints: "https"
      traefik.frontend.whiteList.sourceRange: "192.168.1.0/24"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.4
    container_name: logstash
    networks:
      - elasticsearch-net
      - logstash-net
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    restart: always
    volumes:
      - /home/anton/home/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - /home/anton/home/logstash/config/template.json:/usr/share/logstash/config/template.json:ro
      - /home/anton/home/logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    container_name: kibana
    networks:
      - elasticsearch-net
      - traefik-net
    volumes:
      - /home/anton/home/kibana/config:/usr/share/kibana/config:ro
    restart: always
    depends_on:
      - elasticsearch
    labels:
      traefik.enable: "true"
      traefik.port: 5601
      traefik.frontend.rule: "Host:kibana.anton-johansson.com"
      traefik.frontend.entryPoints: "https"
      traefik.frontend.whiteList.sourceRange: "192.168.1.0/24"

  logspout:
    build:
      context: logspout
    container_name: logspout
    networks:
      - logstash-net
    environment:
      - ROUTE_URIS=logstash://logstash:5000
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - logstash
