version: '2'

services:

  home-assistant:
    image: homeassistant/home-assistant:0.64.0
    container_name: home-assistant
    restart: always
    volumes:
      - /home/anton/home/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0

  deconz:
    image: marthoc/deconz:amd64-2.05.11
    container_name: deconz
    restart: always
    volumes:
      - /home/anton/home/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443

  nginx:
    image: nginx:1.13.11
    container_name: nginx
    restart: always
    volumes:
      - /home/anton/home/nginx/conf.d:/etc/nginx/conf.d
      - /home/anton/home/nginx/certificates:/etc/letsencrypt
      - /home/anton/home/nginx/letsencrypt:/data/letsencrypt
    ports:
      - 80:80
      - 443:443

  influxdb:
    image: influxdb:1.5.1
    container_name: influxdb
    restart: always
    volumes:
      - /home/anton/home/influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:5.0.4
    container_name: grafana
    restart: always
    volumes:
      - /home/anton/home/grafana/data:/var/lib/grafana
