---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  namespace: grafana
data:
  grafana.ini: |
    [log]
    mode = console
    level = info

    [log.console]
    format = json

  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus.prometheus.svc.cluster.local:9090
        isDefault: true
        editable: false
