---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: grafana
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  secretName: grafana-updated-certificate
  dnsNames:
    - grafana.anton-johansson.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
