---
kind: Namespace
apiVersion: v1
metadata:
  name: factorio

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: factorio
  namespace: factorio
  labels:
    app.kubernetes.io/name: factorio
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: factorio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: factorio
    spec:
      containers:
        - name: factorio
          image: factoriotools/factorio:1.1.50
          volumeMounts:
            - name: factorio
              mountPath: /factorio
          ports:
            - name: game
              containerPort: 34197
              protocol: UDP
            - name: rcon
              containerPort: 27015
              protocol: TCP
      volumes:
        - name: factorio
          hostPath:
            path: /opt/factorio

---
kind: Service
apiVersion: v1
metadata:
  name: factorio
  namespace: factorio
  labels:
    app.kubernetes.io/name: factorio
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: factorio
  ports:
    - port: 34197
      nodePort: 32407
      protocol: UDP
