scrape_configs:
  - job_name: 'home-assistant'
    scrape_interval: 60s
    metrics_path: /api/prometheus
    scheme: http
    bearer_token_file: '/etc/prometheus/home-assistant-bearer-token'
    static_configs:
      - targets: ['home-assistant:8123']
