home_latitude: 0.0
home_longitude: 0.0
home_elevation: 0.0
work_latitude: 0.0
work_longitude: 0.0
http_password: example
http_url: https://example.com
http_domain: example.com
portainer_domain: example.com
deconz_domain: example.com
prometheus_domain: example.com
grafana_domain: example.com
speedtest_server_id: 123
tv_hostname: 192.168.0.123
tv_username: example
tv_password: example
chromecast_hostname: 192.168.0.123
sonos_playbar_hostname: 192.168.0.123
sonos_kitchen_hostname: 192.168.0.123
google_calendar_client_id: dummy.apps.googleusercontent.com
google_calendar_shared_secret: dummy
google_calendar_personal_id: personal@example.com
google_calendar_work_id: work@example.com
loopia_username: usr
loopia_password: pw
loopia_domain: example.com
panel_logs: 'https://example.com/app/kibana#/dashboards?title=Application logs&embed'
panel_metrics: 'https://example.com/d/abc123/home?orgId=1&kiosk'
