homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named packages
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret http_password
  base_url: !secret http_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12

zwave:
  usb_path: /dev/zwave

ios:

conversation:

map:

sun:

tts:
  - platform: google

cloud:

panel_iframe:
  application_logs:
    title: Application logs
    icon: mdi:information
    url: http://kibana.anton-johansson.com/app/kibana#/dashboards?title=Application logs&embed

group: !include groups.yaml
script: !include scripts.yaml
zone: !include zones.yaml
