---
kind: Certificate
apiVersion: cert-manager.io/v1alpha2
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  secretName: home-assistant-certificate
  dnsNames:
    - home.anton-johansson.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
