---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: callback-proxy-service
  namespace: callback-proxy-service
  labels:
    app.kubernetes.io/name: callback-proxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: callback-proxy-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: callback-proxy-service
    spec:
      containers:
        - name: callback-proxy-service
          image: antonjohansson/callback-proxy-service:v1.2.1
          ports:
            - name: config
              containerPort: 8181
            - name: proxy
              containerPort: 8182
          volumeMounts:
            - name: config
              mountPath: /etc/callback-proxy-service
              readOnly: true
            - name: data
              mountPath: /var/callback-proxy-service
      volumes:
        - name: config
          configMap:
            name: config
            items:
              - key: config.yaml
                path: callback-proxy-service.yaml
        - name: data
          emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: callback-proxy-service
  namespace: callback-proxy-service
  labels:
    app.kubernetes.io/name: callback-proxy-service
spec:
  selector:
    app.kubernetes.io/name: callback-proxy-service
  ports:
    - name: config
      port: 8181
      protocol: TCP
    - name: proxy
      port: 8182
      protocol: TCP

---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: config
  namespace: callback-proxy-service
  labels:
    app.kubernetes.io/name: callback-proxy-service
    app.kubernetes.io/component: config
  annotations:
    kubernetes.io/ingress.class: internal
spec:
  rules:
    - host: callback-proxy.anton-johansson.local
      http:
        paths:
          - path: /
            backend:
              serviceName: callback-proxy-service
              servicePort: 8181

---
kind: Certificate
apiVersion: cert-manager.io/v1alpha2
metadata:
  name: proxy
  namespace: callback-proxy-service
spec:
  secretName: proxy-certificate
  dnsNames:
    - callback-proxy.anton-johansson.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io

---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: proxy
  namespace: callback-proxy-service
  labels:
    app.kubernetes.io/name: callback-proxy-service
    app.kubernetes.io/component: proxy
  annotations:
    kubernetes.io/ingress.class: external
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
spec:
  rules:
    - host: callback-proxy.anton-johansson.com
      http:
        paths:
          - path: /
            backend:
              serviceName: callback-proxy-service
              servicePort: 8182
  tls:
    - secretName: proxy-certificate
      hosts:
        - callback-proxy.anton-johansson.com
