#
# Handles calendar related information
#

homeassistant:
  customize:
    binary_sensor.workday_today:
      hidden: true
    binary_sensor.workday_tomorrow:
      hidden: true

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_shared_secret
  track_new_calendar: false

binary_sensor:
  - platform: workday
    name: workday_today
    country: SE
    days_offset: 0
  - platform: workday
    name: workday_tomorrow
    country: SE
    days_offset: 1
