#
# Provides information and notifications about the dishwasher.
#

homeassistant:
  customize:
    automation.dishwasher_started:
      hidden: true
    automation.dishwasher_drying:
      hidden: true
    automation.dishwasher_completed:
      hidden: true
    input_select.dishwasher_status:
      hidden: true
    sensor.dishwasher_power_usage:
      friendly_name: Dishwasher power
      icon: mdi:flash
    switch.powerplug_dishwasher:
      hidden: true
  customize_glob:
    sensor.powerplug_dishwasher*:
      hidden: true

input_select:
  dishwasher_status:
    name: dishwasher_status
    options:
      - Idle
      - Drying
      - Running

sensor:
  - platform: template
    sensors:
      dishwasher_power_usage:
        unit_of_measurement: 'W'
        value_template: >-
          {% if states.sensor.powerplug_dishwasher_power.state|float < 5000 %}
            {{ states.sensor.powerplug_dishwasher_power.state }}
          {% else %}
            0
          {% endif %}
      dishwasher_status:
        entity_id:
          - input_select.dishwasher_status
        value_template: "{{ states.input_select.dishwasher_status.state }}"
        icon_template: mdi:dishwasher
        friendly_name: Dishwasher status

automation:
  # Set the dishwasher to running state when the power usage goes up and it is in idle state
  - id: dishwasher_started
    alias: Dishwasher started
    trigger:
      - platform: numeric_state
        entity_id: sensor.dishwasher_power_usage
        above: 10
        for:
          minutes: 1
    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Idle
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Running

  # Set the dishwasher to drying state when power drops and it is in running state
  - id: dishwasher_drying
    alias: Dishwasher drying
    trigger:
      - platform: numeric_state
        entity_id: sensor.dishwasher_power_usage
        below: 5
        for:
          minutes: 1
    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Running
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Drying
      - service: notify.notify
        data:
          title: Dishwasher drying
          message: The dishwasher is currently drying the dishes

  # Set dishwasher to idle state when power drops further and it is in drying state
  - id: dishwasher_completed
    alias: Dishwasher completed
    trigger:
      - platform: numeric_state
        entity_id: sensor.dishwasher_power_usage
        below: 1
        for:
          minutes: 1
    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Idle
      - service: notify.notify
        data:
          title: Dishwasher finished
          message: The dishwasher has finished and is ready to be emptied
      - service: script.sonos_say
        data:
          media_player: living_room
          volume: 0.3
          message: The dishwasher has finished and is ready to be emptied
          delay: 00:00:04

group:
  dishwasher:
    name: Dishwasher
    control: hidden
    entities:
      - sensor.dishwasher_status
      - automation.dishwasher_started
      - automation.dishwasher_drying
      - automation.dishwasher_completed
      - sensor.dishwasher_power_usage
