#
# Adds graphs from Grafana
#

homeassistant:
  customize:
    automation.download_graphs:
      hidden: true
  customize_glob:
    camera.grafana_power_consumption:
      friendly_name: Power consumption

automation:
  - id: download_graphs
    alias: 'Download graphs'
    trigger:
      platform: time
      minutes: '/5'
      seconds: 00
    action:
      service: shell_command.download_graph
      data_template:
        key: !secret grafana_key
        dashboard: anton
        panel: 2
        file: power-consumption.png

camera:
  - platform: local_file
    name: grafana_power_consumption
    file_path: /config/downloads/power-consumption.png

shell_command:
  download_graph: /config/bash/download-graph.sh "{{ key }}" "{{ dashboard }}" "{{ panel }}" "{{ file }}"
