#
# Network
#

homeassistant:
  customize_glob:
    sensor.speedtest_download:
      friendly_name: Download speed
      icon: mdi:download
    sensor.speedtest_upload:
      friendly_name: Upload speed
      icon: mdi:upload
    sensor.speedtest_ping:
      friendly_name: Ping
      icon: mdi:timer
    sensor.myipopendnscom:
      friendly_name: External IP address

group:
  network:
    name: Network
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.myipopendnscom

sensor:
  - platform: speedtest
    monitored_conditions:
      - download
      - upload
      - ping
  - platform: dnsip
    host: myip.opendns.com

automation:
  - alias: notify_when_external_address_changes
    trigger:
      platform: state
      entity_id: sensor.myipopendnscom
    action:
      service: notify.notify
      data_template:
        title: "External IP address changed"
        message: "The external IP address changed to {{ states.sensor.myipopendnscom.state }}."
