#
# Location and state of the cellphone
#

homeassistant:
  customize:
    device_tracker.iphone:
      friendly_name: Location
      icon: mdi:map-marker
    sensor.iphone_battery_level:
      friendly_name: Battery level
    sensor.iphone_battery_state:
      friendly_name: State
    automation.notify_when_location_changes:
      hidden: true

group:
  phone:
    name: Phone
    entities:
      - device_tracker.iphone
      - sensor.iphone_battery_level
      - sensor.iphone_battery_state

automation:
  - id: notify_when_location_changes
    alias: Notify when location changes
    trigger:
      platform: state
      entity_id: device_tracker.iphone
    action:
      service: notify.ios_iphone
      data_template:
        title: "Your location changed"
        message: "Your location changed to '{{ states.device_tracker.iphone.state }}'."
