#
# Provides security related automations
#

homeassistant:
  customize:
    automation.send_notification_when_a_failed_login_attempt_occur:
      hidden: true

automation:
  - id: notify_on_bad_logins
    alias: Send notification when a failed login attempt occur
    trigger:
      - platform: state
        entity_id: persistent_notification.httplogin
    condition:
      - condition: template
        value_template: "{{ states('persistent_notification.httplogin') != 'unknown' }}"
    action:
      - service: notify.notify
        data:
          title: "Failed Home Assistant login attempt!"
          message: "{{ states.persistent_notification.httplogin.attributes.message }}"
      - service: persistent_notification.dismiss
        data:
          notification_id: httplogin
