#
# Controls the Philips TV and related components
#

homeassistant:
  customize:
    script.sonos_say:
      hidden: true

#media_player:
#  - platform: philips_tv_2016
#    name: TV
#    host: !secret tv_hostname
#    username: !secret tv_username
#    password: !secret tv_password

media_player:
  - platform: cast
    host: !secret chromecast_hostname
  - platform: sonos
    hosts:
      - !secret sonos_playbar_hostname

script:
  sonos_say:
    alias: "Sonos TTS script"
    sequence:
     - service: media_player.sonos_snapshot
       data_template:
         entity_id: "{{ 'media_player.' ~ media_player }}"
     - service: media_player.sonos_unjoin
       data_template:
         entity_id: "{{ 'media_player.' ~ media_player }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ 'media_player.' ~ media_player }}"
         volume_level: "{{ volume }}"
     - service: tts.google_say
       data_template:
         entity_id: "{{ 'media_player.' ~ media_player }}"
         message: "{{ message }}"
     - delay: "{{ delay }}"
     - service: media_player.sonos_restore
       data_template:
         entity_id: "{{ 'media_player.' ~ media_player }}"
