#
# Controls the Philips TV and related components
#

homeassistant:
  customize:
    switch.powerplug_tvequipment:
      hidden: true
  customize_glob:
    sensor.powerplug_tvequipment*:
      hidden: true

media_player:
  - platform: philips_android_tv
    name: TV
    host: !secret tv_hostname
    mac: !secret tv_mac
    username: !secret tv_username
    password: !secret tv_password

notify:
  - platform: nfandroidtv
    name: TV
    host: !secret tv_hostname

cast:
  media_player:
    - host: !secret chromecast_hostname
