#
# Controls the Philips TV and related components
#

homeassistant:
  customize:
    switch.powerplug_tvequipment:
      hidden: true
  customize_glob:
    sensor.powerplug_tvequipment*:
      hidden: true

#media_player:
#  - platform: philips_tv_2016
#    name: TV
#    host: !secret tv_hostname
#    username: !secret tv_username
#    password: !secret tv_password

notify:
  - platform: nfandroidtv
    name: TV
    host: !secret tv_hostname

cast:
  media_player:
    - host: !secret chromecast_hostname
