#
# Informs about new Home Assistant versions
#

homeassistant:
  customize:
    automation.notify_on_update_available:
      hidden: true

automation:
  - alias: notify_on_update_available
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.notify
      data_template:
        title: "New Home Assistant version"
        message: "Version {{ states.updater.updater.state }} for Home Assistant is available."
