- alias: 'Washing machine is busy'
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine
      above: 5
  condition:
    condition: state
    entity_id: input_boolean.washing_machine_busy
    state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.washing_machine_busy

- alias: 'Washing machine is ready'
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine
      below: 2
  condition:
    condition: state
    entity_id: input_boolean.washing_machine_busy
    state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.washing_machine_busy
    - service: notify.notify
      data:
        message: 'The washing machine is done!'
