---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: metallb-controller
  namespace: metallb
  labels:
    app.kubernetes.io/name: metallb-controller
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: metallb-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metallb-controller
      annotations:
        prometheus.io/port: '7472'
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      terminationGracePeriodSeconds: 0
      containers:
        - name: metallb-controller
          image: metallb/controller:v0.8.3
          args:
            - --port=7472
            - --config=config
          ports:
            - name: monitoring
              containerPort: 7472
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true

