---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: coredns
  namespace: dns
  labels:
    app.kubernetes.io/name: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dns
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '9153'
    spec:
      containers:
        - name: coredns
          image: coredns/coredns:1.9.0
          resources:
            limits:
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
          args:
            - '-conf'
            - '/etc/coredns/Corefile'
          volumeMounts:
            - name: config
              mountPath: /etc/coredns
              readOnly: true
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: config
          configMap:
            name: coredns
