---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webpage-stage
  namespace: webpage
  labels:
    app.kubernetes.io/name: webpage
    app.kubernetes.io/instance: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webpage
      app.kubernetes.io/instance: stage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webpage
        app.kubernetes.io/instance: stage
    spec:
      containers:
        - name: webpage
          image: antonjohansson/anton-johansson.com:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          env:
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webpage-stage-config
                  key: gmailPassword
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: webpage-stage-config
                  key: spotifyClientID
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: webpage-stage-config
                  key: spotifyClientSecret
            - name: SPOTIFY_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: webpage-stage-config
                  key: spotifyRefreshToken
            - name: STEAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: webpage-stage-config
                  key: steamApiKey
