homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named packages
  customize: !include customize.yaml

frontend:
system_health:
config:
python_script:

http:
  api_password: !secret http_password
  base_url: !secret http_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12

zwave:
  usb_path: /dev/zwave

conversation:

map:

sun:

tts:
  - platform: google_translate
    service_name: google_say

cloud:

group: !include groups.yaml
script: !include scripts.yaml
zone: !include zones.yaml
